projects:
  prisma-graphql-server:
    schemaPath: schema.graphql
    extensions:
      endpoints:
        local:
          url: 'http://localhost:4466/'
          subscription: 'ws://localhost:4466/'
